### ISSUE TITLE
refactor get_next_work

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_tree_pascal#1]
if s[i0][i1] in ['(',')','[',']','/','|','\\','@','#','=','>','<',':',';',',','.','$','+','-','*']:

список надо глобальную константу, напр. SYMBOLS.

s[i0] встреается 10+ раз- надо переменную

**Comment by Alexey-T** [comment]
['>=','<=',':=','..']:

 а это SYMBOLS_2

**Comment by Artem3213212** [comment]
> s[i0] встреается 10+ раз- надо переменную
а i0+=1 видел сколько раз встречается?
