### ISSUE TITLE
Inline

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_tree_pascal#11]
Regexpr.pas

Показывает глоб вар «inline”

**Comment by Artem3213212** [comment]
проверь все такие директивы захватил 'reintroduce','overload','virtual','override','abstract','dynamic','inline'

**Comment by Alexey-T** [comment]
вроде да. Надо константу Капсом.

**Comment by Alexey-T** [comment]
еще 'assembler'

**Comment by Alexey-T** [comment]
еще 'forward'
