### ISSUE TITLE
wrong on file jsonreader.pp

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_tree_pascal#15]
file in tests/ dir.

- not shown class TBaseJsonReader
- and TJsonEventReader
- and TJSONConsumerReader
- words "constructor", "overload" in var-const.

**Comment by Alexey-T** [comment]
не решено. 

- классы TJsonEventReader, TJsonConsumerReader не показаны
- в var - типы TOnJson***

**Comment by Alexey-T** [comment]
- TJsonConsumerReader пока еще не показан
- EJsonParser не показан

**Comment by Alexey-T** [comment]
они без отдельного "type", поэтому?

**Comment by Artem3213212** [comment]
точно нет

**Comment by Alexey-T** [comment]
а почему...

**Comment by Artem3213212** [comment]
перед ними Interface

**Comment by Artem3213212** [comment]
удали его и они распарсятся

**Comment by Alexey-T** [comment]
надо пофиксить, 1 этап почти все.
