### ISSUE TITLE
need support for "interface"

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_tree_pascal#16]
tests/jsonreader.pp

line
  IJSONConsumer = Interface ['{60F9D640-2A69-4AAB-8EE1-0DB6DC614D27}']

можно на этап 2.

**Comment by Artem3213212** [comment]
этап 2

**Comment by Artem3213212** [comment]
хотя этапы сомнительно я уже много сделал из второго но не всё из первого

**Comment by Alexey-T** [comment]
спасибо.
