### ISSUE TITLE
wrong global const

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_tree_pascal#18]
const n must be inside func.
![screenshot from 2018-08-06 22-06-49](https://user-images.githubusercontent.com/4154978/43736078-1f386e82-99c5-11e8-8a2b-fe576b28edf5.png)

ATSynEdit/.../atsynedit_form_complete_synwrite.pas

**Comment by Artem3213212** [comment]
проверь его уже не должно быть

**Comment by Alexey-T** [comment]
Обновил, проверил, баг есть

**Comment by Artem3213212** [comment]
можно файл?

**Comment by Artem3213212** [comment]
я понял в чём дело тоже на второй этап

**Comment by Alexey-T** [comment]
File- указал какой в 1 посте
