### ISSUE TITLE
wrong nodes TName.Method

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_tree_pascal#20]
jsonconf.pp

узлы видны
TJsonConfig.NNNNN
надо же чтобы они были не отдельные узлы а чтобы клик по старым NNNN  внутри TJsonConfig клал каретку на тело ф-ции.

Тоже самое в atsynedit_form_complete_synwrite.pas
видно TAcp.DoLoadNnnn

**Comment by Artem3213212** [comment]
это знаю #7 не закрывал
