### ISSUE TITLE
не строит дерево для atsynedit_sel.inc

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_tree_pascal#39]
файл тут--
https://github.com/Alexey-T/ATSynEdit/tree/master/atsynedit

**Comment by Artem3213212** [comment]
проверил строит

**Comment by Artem3213212** [comment]
![image](https://user-images.githubusercontent.com/37815717/59420796-33051680-8dd6-11e9-9da4-24f722b3d2b7.png)

**Comment by Alexey-T** [comment]
Да, счас ок , и на старой версии от 1.80 тоже ок
