### ISSUE TITLE
Go to implement

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_tree_pascal#7]
Лучше кликом в дереве по методу класса переходить на _реализацию ф-ций а не на class def
e.g. tests/dumpclass.pp

**Comment by Alexey-T** [comment]
то есть переходить на ф-цию в секции implementation а не в строчку в interface.
Это сильно сложно?

**Comment by Artem3213212** [comment]
не сильно но делать надо в самом конце

**Comment by Alexey-T** [comment]
ждем.

**Comment by Alexey-T** [comment]
можно на этап 2.

**Comment by Alexey-T** [comment]
вроде решено. если дописал это- закроем.

**Comment by Alexey-T** [comment]
не решено. tests/jsonconf.pp.
TJsonConfig.DoSetFilename - пргывает на interface decl.

**Comment by Artem3213212** [comment]
проблема в try
