### ISSUE TITLE
codetree sync bug

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_tree_pascal#8]
FPC's regexpr.pas
кажется неверные диапазоны кое где.

- кликкаю на строку в коде function ExecRegExpr  - дерево переходит ее ноде - ОК
- кликаю на слово RegExprInvertCaseFunction в коде

```
const
  RegExprInvertCaseFunction : TRegExprInvertCaseFunction = {$IFDEF FPC} nil {$ELSE} TRegExpr.InvertCaseFunction{$ENDIF};
  // defaul for InvertCase property
```

дерево переходит куда-то не туда. а на ноду класса ERegExpr.

**Comment by Artem3213212** [comment]
нет такого

**Comment by Artem3213212** [comment]
перепроверь

**Comment by Alexey-T** [comment]
Второй пункт все ещё не поправил, в дереве узел RegExprInvertCaseFunct есть, но дерево не ставит на него выделение если ставить каретку

**Comment by Alexey-T** [comment]
Значит узел для ERegExpr захватывает диапазоном и эту константу .. баг

**Comment by Artem3213212** [comment]
там диапазонов нет

**Comment by Alexey-T** [comment]
Понял , это баг cuda_tree
